#!/usr/bin/env python3
"""Create the offline browser data from MTX.xml (Python standard library only)."""

import argparse
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET


def fields(element):
    return {child.tag: child.text or "" for child in element} if element is not None else {}


def build(source, destination):
    data = {"catalogue": {}, "version": {}, "hierarchies": [], "attributes": [], "terms": []}
    stack = []
    for event, element in ET.iterparse(source, events=("start", "end")):
        if event == "start":
            stack.append(element)
            continue
        tag = element.tag
        parent = stack[-2] if len(stack) > 1 else None
        if tag == "catalogueDesc":
            data["catalogue"] = fields(element)
        elif tag == "catalogueVersion":
            data["version"] = fields(element)
        elif tag == "hierarchy" and parent.tag == "catalogueHierarchies":
            data["hierarchies"].append(fields(element.find("hierarchyDesc")))
        elif tag == "attribute" and parent.tag == "catalogueAttributes":
            data["attributes"].append(fields(element.find("attributeDesc")))
        elif tag == "term" and parent.tag == "catalogueTerms":
            desc = fields(element.find("termDesc"))
            term = {
                "code": desc.pop("termCode"),
                "name": desc.pop("termExtendedName", ""),
                "note": desc.pop("termScopeNote", ""),
                "extra": desc,
                "version": fields(element.find("termVersion")),
                "assignments": [fields(a) for a in element.findall("hierarchyAssignments/hierarchyAssignment")],
                "attributes": {},
            }
            for attribute in element.findall("implicitAttributes/implicitAttribute"):
                code = attribute.findtext("attributeCode")
                term["attributes"].setdefault(code, []).extend(
                    value.text or "" for value in attribute.findall("attributeValues/attributeValue")
                )
            data["terms"].append(term)
            parent.remove(element)
        stack.pop()

    codes = [term["code"] for term in data["terms"]]
    if not codes or len(codes) != len(set(codes)):
        raise ValueError("Katalogen er tom eller inneholder dupliserte termkoder")
    with source.open("rb") as handle:
        checksum = hashlib.file_digest(handle, "sha256").hexdigest()
    data["source"] = {"file": source.name, "sha256": checksum}
    # Classic script (not fetch/modules) deliberately supports file:// URLs.
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    payload = payload.replace("<", "\\u003c").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    destination.write_text("// Generated by build_catalogue.py; do not edit.\nwindow.MTX_DATA=" + payload + ";\n", encoding="utf-8")
    print(f"{len(codes):,} termer, {len(data['hierarchies'])} hierarkier, "
          f"{len(data['attributes'])} attributter → {destination.name} "
          f"({destination.stat().st_size / 1024 / 1024:.1f} MiB)")


if __name__ == "__main__":
    directory = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", nargs="?", type=Path, default=directory / "MTX.xml")
    parser.add_argument("--output", type=Path, default=directory / "catalogue-data.js")
    args = parser.parse_args()
    build(args.source, args.output)
